name: Docker Hub - Publish Image

on:
  push:
    branches:
      - main

jobs:
  dockerhub-publish-image:
    runs-on: ubuntu-latest

    steps:
      - name: Github - Checkout
        uses: actions/checkout@v4

      - name: Docker - Login to Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker - Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/steamgifts-bot:latest
